inputs:
  python-version:
    description: 'py ver'
    required: true
    default: '3.9'

name: Update requirements
runs-on: ubuntu-latest
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Update requirements
      shell: bash
      run: echo env py ver is $PYTHON_VERSION
