inputs:
  python-version:
    description: 'py ver'
    required: true
    default: '3.9'

name: Update requirements
runs-on: ubuntu-latest
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Update requirements
      shell: bash
      run: |
        pip install --requirement requirements/local_build.txt
        inv project.install-tools
        inv project.pip-compile --update
